package:
  name: ompeval
  version: 0.0.11

source:
  path: ..

build:
  number: 0
  script: python -m pip install . -vvv

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - cmake
    - ninja

  host:
    - python
    - pip

  run:
    - python
    - numpy

test:
  requires:
    - pytest
    - numpy
  imports:
    - ompeval
  source_files:
    - tests
  commands:
    - python -m pytest

about:
  summary: Python Wrapper for OMPEval.
  license_file: LICENSE
